version: '3'

volumes:
  db_data:
  composer-cache:
  vendor:

services:
  reverse-proxy:
    container_name: wild-and-without-proxy
    image: traefik:v2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=aydin@hotmail.co.uk"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/files/acme.json:/letsencrypt/acme.json
    labels:
      traefik.enable: true
      traefik.http.routers.http_catchall.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.http_catchall.entrypoints: web
      traefik.http.routers.http_catchall.middlewares: https_redirect
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https_redirect.redirectscheme.permanent: true

  php:
    container_name: wild-and-without-fpm
    build:
      context: .
      dockerfile: .docker/files/wild-and-without-fpm/Dockerfile
    volumes:
      - ./.env:/var/www/html/.env
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./public:/var/www/html/public
      - vendor:/var/www/html/vendor
      - composer-cache:/home/www-data/.composer/cache
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=wild_and_without
      - MYSQL_USER=wild_and_without
      - MYSQL_PASSWORD=wild_and_without
      - DEBUG_MODE=true
      - PHP_IDE_CONFIG=serverName=wildandwithout
      - XDEBUG_CONFIG=remote_host=docker.for.mac.localhost remote_port=9001
    depends_on:
      - "db"

  db:
    container_name: wild-and-without-db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wild_and_without
      - MYSQL_USER=wild_and_without
      - MYSQL_PASSWORD=wild_and_without

  varnish:
    container_name: wild-and-without-varnish
    build:
      context: .docker/files/wild-and-without-varnish
      dockerfile: Dockerfile
    restart: always
    environment:
      VARNISH_PURGE_KEY: "${VARNISH_PURGE_KEY}"
    logging:
      options:
        max-size: 10m
    labels:
      traefik.enable: true
      traefik.http.middlewares.admin-redirect.redirectregex.regex: ^https://www.wildandwithout.local/admin/(.*)
      traefik.http.middlewares.admin-redirect.redirectregex.replacement: https://www.wildandwithout.local/wp/wp-admin/$${1}
      traefik.http.middlewares.admin-redirect.redirectregex.permanent: true
      traefik.http.middlewares.nonwww-redirect.redirectregex.regex: ^https://wildandwithout.local/(.*)
      traefik.http.middlewares.nonwww-redirect.redirectregex.replacement: https://www.wildandwithout.local/$${1}
      traefik.http.middlewares.nonwww-redirect.redirectregex.permanent: true
      traefik.http.routers.varnish-websecure.rule: Host(`www.wildandwithout.local`, `wildandwithout.local`)
      traefik.http.routers.varnish-websecure.middlewares: nonwww-redirect, admin-redirect
      traefik.http.routers.varnish-websecure.entrypoints: websecure
      traefik.http.routers.varnish-websecure.tls.certresolver: myresolver
    depends_on:
      - "nginx"

  nginx:
    container_name: wild-and-without-nginx
    image: nginx:latest
    links:
      - php
    volumes:
      - .docker/files/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - vendor:/var/www/html/vendor

  dockerhost:
    container_name: wild-and-without-host
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: always
