version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=aydin@hotmail.co.uk"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .docker/files/acme.json:/letsencrypt/acme.json
    labels:
      traefik.enable: true
      traefik.http.routers.http_catchall.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.http_catchall.entrypoints: web
      traefik.http.routers.http_catchall.middlewares: https_redirect
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https_redirect.redirectscheme.permanent: true

  php:
    container_name: wild-and-without-fpm
    build:
      context: .
      dockerfile: .docker/files/wild-and-without-fpm/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=wild_and_without
      - MYSQL_USER=wild_and_without
      - MYSQL_PASSWORD=wild_and_without
      - DEBUG_MODE=true
      - PHP_IDE_CONFIG=serverName=wildandwithout
      - XDEBUG_CONFIG=remote_host=docker.for.mac.localhost remote_port=9001
    depends_on:
      - "db"

  db:
    container_name: wild-and-without-db
    image: mysql:5.7
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
      - "./.docker/db/:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wild_and_without
      - MYSQL_USER=wild_and_without
      - MYSQL_PASSWORD=wild_and_without

  varnish:
    build:
      context: .docker/files/wild-and-without-varnish
      dockerfile: Dockerfile
    restart: always
    logging:
      options:
        max-size: 10m
    labels:
      traefik.enable: true
      traefik.http.middlewares.nonwww-redirect.redirectregex.regex: ^https://wildandwithout.local/(.*)
      traefik.http.middlewares.nonwww-redirect.redirectregex.replacement: https://www.wildandwithout.local/$${1}
      traefik.http.middlewares.nonwww-redirect.redirectregex.permanent: true
      traefik.http.routers.varnish-websecure.rule: Host(`www.wildandwithout.local`, `wildandwithout.local`)
      traefik.http.routers.varnish-websecure.middlewares: nonwww-redirect
      traefik.http.routers.varnish-websecure.entrypoints: websecure
      traefik.http.routers.varnish-websecure.tls.certresolver: myresolver
    depends_on:
      - "nginx"

  nginx:
    container_name: wild-and-without-nginx
    image: nginx:latest
    links:
      - php
    volumes:
      - .docker/files/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: always
