version: '3'

volumes:
  db_data:
  composer-cache:
  vendor:

services:
  php:
    container_name: wild-and-without-fpm
    build:
      context: .
      dockerfile: .docker/files/wild-and-without-fpm/Dockerfile
    volumes:
      - ./.env:/var/www/html/.env
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - vendor:/var/www/html/vendor
      - composer-cache:/home/www-data/.composer/cache
      - type: bind
        source: ./public
        target: /var/www/html/public
        consistency: cached
    environment:
      - PHP_IDE_CONFIG=serverName=wildandwithout
      - XDEBUG_CONFIG=remote_host=docker.for.mac.localhost remote_port=9001
    depends_on:
      - "db"

  db:
    container_name: wild-and-without-db
    image: mariadb:latest
    platform: 'linux/x86_64'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wild_and_without
      - MYSQL_USER=wild_and_without
      - MYSQL_PASSWORD=wild_and_without

  nginx:
    container_name: wild-and-without-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - .docker/files/nginx.conf:/etc/nginx/conf.d/default.conf
      - vendor:/var/www/html/vendor
      - type: bind
        source: ./public
        target: /var/www/html/public
        consistency: cached

  redis:
    container_name: wild-and-without-redis
    image: redis:latest
    ports:
      - "6379"