version: '2'

services:
  php:
    container_name: wild-and-without-fpm
    build:
      context: .
      dockerfile: .docker/files/wild-and-without-fpm/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=phpschool
      - MYSQL_USER=phpschool
      - MYSQL_PASSWORD=phpschool
      - DEBUG_MODE=true
      - XDEBUG_CONFIG="idekey=PHPSTORM"
    ports:
      - 9000
    depends_on:
      - "db"

  db:
    container_name: wild-and-without-db
    image: mysql:5.7
    volumes:
      - "./.docker/mysql:/var/lib/mysql"
      - "./.docker/db/:/docker-entrypoint-initdb.d/"
    ports:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wild_and_without
      - MYSQL_USER=wild_and_without
      - MYSQL_PASSWORD=wild_and_without

  nginx:
    container_name: wild-and-without-nginx
    image: nginx:latest
    links:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - .docker/certs:/etc/ssl/certs
      - .docker/files/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  redis:
    container_name: wild-and-without-redis
    image: redis
    ports:
      - "6379"
